### ISSUE TITLE
Discourse DB import

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/LegacySpongeAuth#3]
Needs to be able to import a Discourse database and support Discourse's password hashes and account metadata.

**Comment by windy1** [comment]
Can you please clarify what you mean by account metadata.

**Comment by windy1** [comment]
[This script](https://github.com/windy1/SpongeAuth/blob/master/scripts/importDiscourseUsers.py) will import users and custom user fields from Discourse.

First run the script parameterlessly and then with `--customFields`.

**Comment by windy1** [comment]
I have also tested this with a local Discourse installation and everything is working as expected.
