### ISSUE TITLE
Port new dropdown style

### ISSUE THREAD

**Issue by windy1** [SpongePowered/LegacySpongeAuth#4]
@Minecrell would you mind handling this one if you find some time? It should be pretty similar to Ore, I copy/pasted most of the css and base templates from there anyways.

**Comment by progwml6** [comment]
@windy1 can this be put into spongeplay to avoid the need to update in both places in the future??

**Comment by windy1** [comment]
The CSS isn't shared because it just becomes to confusing we change something to fix something in one project it might cause unintended effects in another. Such is the nature of CSS, which is why I opted to go the copy/paste method for CSS :P
